/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/navigation" />

// NOTE: This file should not be edited manually
// It is auto-generated by Next.js when running the dev server or build process

// Extend ProcessEnv interface for typed environment variables
declare namespace NodeJS {
  interface ProcessEnv {
    readonly NEXT_PUBLIC_API_URL: string;
    readonly NEXT_PUBLIC_SOCKET_URL: string;
  }
}

// Extend JSX namespace for Next.js specific elements
declare namespace JSX {
  interface IntrinsicElements extends React.JSX.IntrinsicElements {
    // Next.js specific JSX elements are automatically included
  }
}

// Extend Image interface for Next.js Image component props
interface ImageProps extends HTMLImageElement {
  loading?: 'lazy' | 'eager';
  priority?: boolean;
}

// Ensure modules with .css imports are properly typed
declare module '*.css' {
  const content: { [className: string]: string };
  export default content;
}

// Ensure modules with static file imports are properly typed
declare module '*.svg' {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}

declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.jpg' {
  const content: string;
  export default content;
}

declare module '*.jpeg' {
  const content: string;
  export default content;
}

declare module '*.gif' {
  const content: string;
  export default content;
}

declare module '*.webp' {
  const content: string;
  export default content;
}

// Add support for importing JSON files
declare module '*.json' {
  const content: any;
  export default content;
}