# MongoDB Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: lead-capture-platform
  labels:
    app: mongodb
    tier: database
    environment: production
    managed-by: platform-team
type: Opaque
data:
  # MongoDB root credentials for initial setup and administration
  root-username: PHJvb3RfdXNlcm5hbWU+  # base64 encoded value
  root-password: PHJvb3RfcGFzc3dvcmQ+  # base64 encoded value
  # Full connection string with auth and options
  connection-string: PG1vbmdvZGJfdXJpX3N0cmluZz4=  # base64 encoded value
  # Field-level encryption key
  encryption-key: PG1vbmdvZGJfZW5jcnlwdGlvbl9rZXk+  # base64 encoded value
---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: lead-capture-platform
  labels:
    app: redis
    tier: cache
    environment: production
    managed-by: platform-team
type: Opaque
data:
  # Redis authentication credentials
  redis-password: PHJlZGlzX3Bhc3N3b3JkPg==  # base64 encoded value
  # Redis data encryption key
  encryption-key: PHJlZGlzX2VuY3J5cHRpb25fa2V5Pg==  # base64 encoded value
---
# SMS Provider Secrets
apiVersion: v1
kind: Secret
metadata:
  name: sms-provider-secrets
  namespace: lead-capture-platform
  labels:
    app: sms-service
    tier: external
    environment: production
    managed-by: platform-team
type: Opaque
data:
  # SMS provider authentication and security
  api-key: PHNtc19hcGlfa2V5Pg==  # base64 encoded value
  api-secret: PHNtc19hcGlfc2VjcmV0Pg==  # base64 encoded value
  webhook-secret: PHNtc193ZWJob29rX3NlY3JldD4=  # base64 encoded value
  # SMS content encryption key
  encryption-key: PHNtc19lbmNyeXB0aW9uX2tleT4=  # base64 encoded value
---
# AI Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: lead-capture-platform
  labels:
    app: ai-service
    tier: external
    environment: production
    managed-by: platform-team
type: Opaque
data:
  # AI service authentication and configuration
  api-key: PGFpX2FwaV9rZXk+  # base64 encoded value
  model-config: PGFpX21vZGVsX2NvbmZpZz4=  # base64 encoded value
  rate-limit-key: PGFpX3JhdGVfbGltaXRfa2V5Pg==  # base64 encoded value
  # AI data encryption key
  encryption-key: PGFpX2VuY3J5cHRpb25fa2V5Pg==  # base64 encoded value